[package]
name = "netwatch_cli"
version = "0.1.0"
authors = ["acheronfail"]
edition = "2018"

[dependencies]
netwatch = { path = "../netwatch"}
pnet = "0.23.0"

crossterm = "0.14"
tui = { version = "0.8", default-features = false, features = ['crossterm'] }
